version: '2'
services:
  # mongo service
  db:
    image: mongo:3.2.3
  # node-loopback rest api service
  api:
    build: ./server-node
    links:
      - db
  # nginx service to serve static client files
  nginx:
    build:
      context: ./client-angular
      dockerfile: Dockerfile-nginx
  # client builder service to build static files for nginx
  client:
    build: ./client-angular
    volumes:
      - ./client-angular/build:/app/build
