# dev environment overrides for docker-compose
version: '2'
services:
  api:
    depends_on:
      - sumologiccollector
    environment:
      NODE_ENV: 'production'

  client:
    environment:
      NODE_ENV: 'production'

  # sumologic log collector service
  sumologiccollector:
    # Folder containing Dockerfile to build the sumologic collector    image
    build: ./sumologiccollector
    volumes:
      # to access to docker logs
      - /var/run/docker.sock:/var/run/docker.sock