# dev environment overrides for docker-compose
version: '2'
services:
  db:
    # expose server for debugging
    ports: 
      - '27017:27017'
  api:
    build:
      context: ./server-node
      dockerfile: Dockerfile-dev
    ports: 
      - '3000:3000'
    #mount code as volume
    volumes:
      - ./server-node:/app
    working_dir: /app 
  nginx:
    build:
      context: ./client-angular
      dockerfile: Dockerfile-nginx-dev
    ports:
     - '80:8080'
     - '443:4433'
    # client link used for browser-sync proxy
    links:
      - client
  client:
    build:
      context: ./client-angular
      dockerfile: Dockerfile-dev
    #mount code as volume
    volumes:
      - ./client-angular:/app
    working_dir: /app