version: '2'
services:
  # mongo service
  db:
    image: mongo
  # node-loopback rest api server
  api:
    # sets where the Dockerfile will be to build the image
    build: ./server-node
    ports: 
      - '3000:3000'
    links:
      - db
  # nginx container to serve static client files
  nginx:
    build:
      context: ./client-angular
      dockerfile: Dockerfile-nginx
    ports:
     - '80:80'
     - '443:443'
  # client builder container to build static files for nginx
  client:
    build: ./client-angular

  sumologiccollector:
    # Folder containing Dockerfile to build the sumologic collector    image
    build: ./sumologiccollector
    volumes:
      # to access to docker logs
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      # m21lab@macadamian.com
      SUMO_ACCESS_ID: 'su7UEd74j6rmWm'
      SUMO_ACCESS_KEY: 'f02R677gpCijdUcAIQ5Pu38To5klQgRWcHYueLOb5Hlfxc8xslWHxz3Pq2y2M3Q6'
      SUMO_COLLECTOR_NAME: 'boilerangularloop'
