FROM node:5.6

# Create app directory
RUN mkdir -p /app
WORKDIR /app

# Install app dependencies
COPY ["./package.json", "./bower.json", "./.bowerrc", "/app/"]
RUN npm install --no-optional --unsafe-perm

# Copy code
COPY . /app

# Run as root to output test results file

# Run the tests
CMD [ "npm", "bambooTest" ]
