FROM nginx:1.9

# Create app directory
RUN mkdir -p /app
WORKDIR /app

# copy over nginx configuration
COPY  ./nginx.conf /etc/nginx/nginx.conf

# copy built files over
COPY ./build /app/www

# switch to non root user
RUN chown -R nobody /app
USER nobody